[package]
name = "lib_geoip_rust"
version = "0.1.0"
edition = "2021"

[lib]
name       = "geopip_rust"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.158"
memmap2 = "0.9.5"
positioned-io = "0.3.3"
